bwm: pybind11

diff --git a/build-with-meson/mk b/build-with-meson/mk
--- a/build-with-meson/mk
+++ b/build-with-meson/mk
@@ -2,31 +2,46 @@
 
 BUILD_DEFAULT_DIR=build
 BUILD_DEBUG_DIR=build.debug
+BUILD_DIR="${BUILD_DEFAULT_DIR}"
+SETUP_ARGS=-Doptimization=3
+BUILT=NO
+
+# ----------------------------------------------------------------------
+
+build()
+{
+    trap 'fail "build failed"' ERR
+    if [[ ! -d "${BUILD_DIR}" ]]; then
+        find_compiler
+        meson setup "${BUILD_DIR}" -Ddebug=true ${SETUP_ARGS}
+        # --buildtype debugoptimized
+        # -Dcpp_args=-O3
+    fi
+    ${MK_TIME} meson compile -C "${BUILD_DIR}"
+    BUILT=YES
+}
 
 # ----------------------------------------------------------------------
 
 build_default()
 {
-    trap 'fail "build failed"' ERR
-    if [[ ! -d "${BUILD_DEFAULT_DIR}" ]]; then
-        find_compiler
-        meson setup "${BUILD_DEFAULT_DIR}" -Ddebug=true -Doptimization=3
-        # --buildtype debugoptimized
-        # -Dcpp_args=-O3
-    fi
-    ${MK_TIME} meson compile -C "${BUILD_DEFAULT_DIR}"
+    build
 }
 
 # ----------------------------------------------------------------------
 
 build_debug()
 {
-    trap 'fail "build failed"' ERR
-    if [[ ! -d "${BUILD_DEBUG_DIR}" ]]; then
-        find_compiler
-        meson setup "${BUILD_DEBUG_DIR}"  -Ddebug=true -Doptimization=g -Db_sanitize=address
-    fi
-    ${MK_TIME} meson compile -C "${BUILD_DEBUG_DIR}"
+    BUILD_DIR="${BUILD_DEBUG_DIR}"
+    SETUP_ARGS=-Doptimization=g -Db_sanitize=address
+    build
+}
+
+# ----------------------------------------------------------------------
+
+run_test()
+{
+    meson test -C "${BUILD_DIR}"
 }
 
 # ----------------------------------------------------------------------
@@ -80,16 +95,24 @@ fail()
 
 trap 'fail "build failed"' ERR
 cd "$(dirname $0)"
-case "$1" in
-    clean)
-        clean
-        ;;
-    debug)
-        build_debug
-        ;;
-    -h)
-        fail "Usage: $0 [-h] [clean] [debug]"
-        ;;
-    *)
-        build_default
-esac
+for arg in "$@"; do
+    case "${arg}" in
+        clean)
+            clean
+            ;;
+        debug)
+            build_debug
+            ;;
+        test)
+            run_test
+            ;;
+        -h)
+            fail "Usage: $0 [-h] [clean] [debug] [test]"
+            ;;
+        *)
+            fail "Unknown arg: ${arg}"
+    esac
+done
+if [ $# == 0 ]; then
+    build_default
+fi
